// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team6651.robot.subsystems;

import org.usfirst.frc.team6651.robot.RobotMap;
import org.usfirst.frc.team6651.robot.OI;
import org.usfirst.frc.team6651.robot.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;

import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class DriveTrain extends Subsystem {

	Spark rightFront = new Spark(1);
	Spark rightBack = new Spark(2);
	SpeedControllerGroup m_right = new SpeedControllerGroup(rightFront, rightBack);
	Spark leftFront = new Spark(4);
	Spark leftBack = new Spark(5);
	SpeedControllerGroup m_left = new SpeedControllerGroup(leftFront, leftBack);
	// m_left.setInverted(false);
	DifferentialDrive DT = new DifferentialDrive(m_right, m_left);
	Spark slider = new Spark(6);
	
    @Override
    public void initDefaultCommand() {
    		// setDefaultCommand(new DriveTrain());
    }


    public void DrivePS4 (double forward, double turn, double slideSpeed) 
    {
    		DT.arcadeDrive(forward, turn);
    		slider.set(slideSpeed);
    }



}

