// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team6651.robot;

// import org.usfirst.frc.team6651.robot.commands.*;
// import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
// import edu.wpi.first.wpilibj.Joystick.AxisType;
// import org.usfirst.frc.team6651.robot.subsystems.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {

    public Joystick joy1, joy2;

    public OI() {
        joy1 = new Joystick(0);
        joy2 = new Joystick(1);
        
      /*  
        
        
        public JoystickButton SlideRight;
        public JoystickButton SLideLeft;
        
        SlideRight = new JoystickButton(joystickDrive, 8);
        SlideRight.whileHeld(new slide(.5));
        
        SlideLeft = new JoystickButton(joystickDrive, 7);
        SlideLeft.whileHeld(new slide(-.5));

        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("Slide", new Slide());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS */
    }

    public Joystick getJoy1() {
        return joy1;
    }
    
    public Joystick getJoy2() {
        return joy2;
    }
    
    public double getJoy1Axis(int axis) {
        return joy1.getRawAxis(axis);
    }
    
    public double getJoy2Axis(int axis) {
    		return joy2.getRawAxis(axis);
    }
}

